# 日期
20170627

# 問題
dataframe的列可以用指定排序
行列对应关系不被破坏, 排列出最大的20%的数

# 行動
~ 参考资料
- [使用Pandas对数据进行筛选和排序](http://bluewhale.cc/2016-08-06/use-pandas-filter-and-sort.html)
- PythonDataScienceHandbook.sorting arrays.P85

## 行動1
- np.sort(data, axis=0)
- 行列关系打破很危险

## 行動2
- 抛弃行列关系
- 用np.sort()排序单项活动

# 經驗教訓
1. 能被计算只能是series或array
2. dataframe只是用来存储
3. 计算是单条的; 存储是成片的

# 反饋

----

### 行动1

In [16]:
import pandas as pd
import numpy as np

In [17]:
X = rand.randint(0, 10, (4, 6))

In [20]:
X

array([[8, 0, 9, 2, 6, 3],
       [8, 2, 4, 2, 6, 4],
       [8, 6, 1, 3, 8, 1],
       [9, 8, 9, 4, 1, 3]])

In [19]:
# 将X按列排序
np.sort(X, axis=0)

array([[8, 0, 1, 2, 1, 1],
       [8, 2, 4, 2, 6, 3],
       [8, 6, 9, 3, 6, 3],
       [9, 8, 9, 4, 8, 4]])

`注意：用sort axis导致行和列的对应关系完全被打破！非常危险！`

### 行动2

In [21]:
import pandas as pd
import numpy as np
py = pd.Series({'2017-06-26': 2, 
                '2017-06-27': 3.5, 
                '2017-06-28': 2, 
                '2017-06-29': 1, 
                '2017-06-30': 0, 
                '2017-07-01': 4, 
                '2017-07-02': 1})
cost = pd.Series({'2017-06-26': 12, 
                '2017-06-27': 13.5, 
                '2017-06-28': 12, 
                '2017-06-29': 11, 
                '2017-06-30': 10, 
                '2017-07-01': 14, 
                '2017-07-02': 11})
play = pd.Series({'2017-06-26': 4, 
                '2017-06-27': 7, 
                '2017-06-28': 4.5, 
                '2017-06-29': 2, 
                '2017-06-30': 4, 
                '2017-07-01': 6, 
                '2017-07-02': 3})

In [22]:
py

2017-06-26    2.0
2017-06-27    3.5
2017-06-28    2.0
2017-06-29    1.0
2017-06-30    0.0
2017-07-01    4.0
2017-07-02    1.0
dtype: float64

In [23]:
np.sort(py)

array([ 0. ,  1. ,  1. ,  2. ,  2. ,  3.5,  4. ])

问:array可以转为dataframe吗？

答:array与series的关系比较亲

In [25]:
type(py)

pandas.core.series.Series

问:dataframe可以直接进行排序吗？
    
答:
1. dataframe似乎是存储为主,不适合做计算
2. array或series更适合计算